# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectWindow(object):
    def setupUi(self, ProjectWindow):
        ProjectWindow.setObjectName("ProjectWindow")
        ProjectWindow.resize(1200, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProjectWindow.sizePolicy().hasHeightForWidth())
        ProjectWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ProjectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1201, 891))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.color_label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_1.setText("")
        self.color_label_1.setObjectName("color_label_1")
        self.verticalLayout.addWidget(self.color_label_1)
        self.color_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_2.setText("")
        self.color_label_2.setObjectName("color_label_2")
        self.verticalLayout.addWidget(self.color_label_2)
        self.color_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_3.setText("")
        self.color_label_3.setObjectName("color_label_3")
        self.verticalLayout.addWidget(self.color_label_3)
        self.color_label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_4.setText("")
        self.color_label_4.setObjectName("color_label_4")
        self.verticalLayout.addWidget(self.color_label_4)
        self.color_label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_5.setText("")
        self.color_label_5.setObjectName("color_label_5")
        self.verticalLayout.addWidget(self.color_label_5)
        self.color_label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_6.setText("")
        self.color_label_6.setObjectName("color_label_6")
        self.verticalLayout.addWidget(self.color_label_6)
        self.color_label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_7.setText("")
        self.color_label_7.setObjectName("color_label_7")
        self.verticalLayout.addWidget(self.color_label_7)
        self.color_label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.color_label_8.setText("")
        self.color_label_8.setObjectName("color_label_8")
        self.verticalLayout.addWidget(self.color_label_8)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1200, 900))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1210, 881))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.space_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.space_2.setText("")
        self.space_2.setObjectName("space_2")
        self.horizontalLayout.addWidget(self.space_2)
        self.label_for_image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_for_image.setMinimumSize(QtCore.QSize(900, 600))
        self.label_for_image.setText("")
        self.label_for_image.setObjectName("label_for_image")
        self.horizontalLayout.addWidget(self.label_for_image)
        self.space_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.space_1.setText("")
        self.space_1.setObjectName("space_1")
        self.horizontalLayout.addWidget(self.space_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.image_worker = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        self.image_worker.setMinimumSize(QtCore.QSize(1120, 240))
        self.image_worker.setMaximumSize(QtCore.QSize(1136, 16777215))
        self.image_worker.setObjectName("image_worker")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.lumislider = QtWidgets.QSlider(self.page_5)
        self.lumislider.setGeometry(QtCore.QRect(260, 50, 851, 51))
        self.lumislider.setMinimum(-150)
        self.lumislider.setMaximum(150)
        self.lumislider.setProperty("value", 0)
        self.lumislider.setSliderPosition(0)
        self.lumislider.setOrientation(QtCore.Qt.Horizontal)
        self.lumislider.setObjectName("lumislider")
        self.conslider = QtWidgets.QSlider(self.page_5)
        self.conslider.setGeometry(QtCore.QRect(260, 110, 851, 51))
        self.conslider.setMinimum(-150)
        self.conslider.setMaximum(150)
        self.conslider.setProperty("value", 0)
        self.conslider.setTracking(True)
        self.conslider.setOrientation(QtCore.Qt.Horizontal)
        self.conslider.setInvertedAppearance(False)
        self.conslider.setInvertedControls(False)
        self.conslider.setObjectName("conslider")
        self.label_luminance = QtWidgets.QLabel(self.page_5)
        self.label_luminance.setGeometry(QtCore.QRect(20, 60, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setItalic(True)
        self.label_luminance.setFont(font)
        self.label_luminance.setObjectName("label_luminance")
        self.label_contrast = QtWidgets.QLabel(self.page_5)
        self.label_contrast.setGeometry(QtCore.QRect(20, 120, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setItalic(True)
        self.label_contrast.setFont(font)
        self.label_contrast.setObjectName("label_contrast")
        self.accept_luminance = QtWidgets.QPushButton(self.page_5)
        self.accept_luminance.setGeometry(QtCore.QRect(20, 190, 1091, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.accept_luminance.setFont(font)
        self.accept_luminance.setObjectName("accept_luminance")
        self.lumilabel = QtWidgets.QLabel(self.page_5)
        self.lumilabel.setGeometry(QtCore.QRect(0, 0, 1135, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.lumilabel.setFont(font)
        self.lumilabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lumilabel.setObjectName("lumilabel")
        self.lum_value_flag = QtWidgets.QLabel(self.page_5)
        self.lum_value_flag.setGeometry(QtCore.QRect(670, 95, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lum_value_flag.setFont(font)
        self.lum_value_flag.setAlignment(QtCore.Qt.AlignCenter)
        self.lum_value_flag.setObjectName("lum_value_flag")
        self.lum_value_flag_2 = QtWidgets.QLabel(self.page_5)
        self.lum_value_flag_2.setGeometry(QtCore.QRect(230, 90, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lum_value_flag_2.setFont(font)
        self.lum_value_flag_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lum_value_flag_2.setObjectName("lum_value_flag_2")
        self.lum_value_flag_3 = QtWidgets.QLabel(self.page_5)
        self.lum_value_flag_3.setGeometry(QtCore.QRect(1080, 90, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lum_value_flag_3.setFont(font)
        self.lum_value_flag_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lum_value_flag_3.setObjectName("lum_value_flag_3")
        self.image_worker.addWidget(self.page_5)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.lumilabel_2 = QtWidgets.QLabel(self.page_10)
        self.lumilabel_2.setGeometry(QtCore.QRect(0, 0, 1135, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.lumilabel_2.setFont(font)
        self.lumilabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lumilabel_2.setObjectName("lumilabel_2")
        self.open_color_dialog = QtWidgets.QPushButton(self.page_10)
        self.open_color_dialog.setGeometry(QtCore.QRect(450, 90, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.open_color_dialog.setFont(font)
        self.open_color_dialog.setObjectName("open_color_dialog")
        self.image_worker.addWidget(self.page_10)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.color_mixing_func_label = QtWidgets.QLabel(self.page_6)
        self.color_mixing_func_label.setGeometry(QtCore.QRect(0, 0, 1135, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_mixing_func_label.sizePolicy().hasHeightForWidth())
        self.color_mixing_func_label.setSizePolicy(sizePolicy)
        self.color_mixing_func_label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.color_mixing_func_label.setFont(font)
        self.color_mixing_func_label.setAlignment(QtCore.Qt.AlignCenter)
        self.color_mixing_func_label.setObjectName("color_mixing_func_label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_6)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 1091, 217))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yellow_button_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.yellow_button_2.setMinimumSize(QtCore.QSize(0, 176))
        self.yellow_button_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.yellow_button_2.setText("")
        self.yellow_button_2.setObjectName("yellow_button_2")
        self.colormix_buttons = QtWidgets.QButtonGroup(ProjectWindow)
        self.colormix_buttons.setObjectName("colormix_buttons")
        self.colormix_buttons.addButton(self.yellow_button_2)
        self.gridLayout_2.addWidget(self.yellow_button_2, 1, 1, 1, 1)
        self.cyan_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.cyan_button.setMinimumSize(QtCore.QSize(0, 176))
        self.cyan_button.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.cyan_button.setText("")
        self.cyan_button.setObjectName("cyan_button")
        self.colormix_buttons.addButton(self.cyan_button)
        self.gridLayout_2.addWidget(self.cyan_button, 1, 3, 1, 1)
        self.green_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.green_button.setMinimumSize(QtCore.QSize(0, 176))
        self.green_button.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.green_button.setText("")
        self.green_button.setObjectName("green_button")
        self.colormix_buttons.addButton(self.green_button)
        self.gridLayout_2.addWidget(self.green_button, 1, 2, 1, 1)
        self.blue_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.blue_button.setMinimumSize(QtCore.QSize(0, 176))
        self.blue_button.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.blue_button.setText("")
        self.blue_button.setObjectName("blue_button")
        self.colormix_buttons.addButton(self.blue_button)
        self.gridLayout_2.addWidget(self.blue_button, 1, 4, 1, 1)
        self.red_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.red_button.setMinimumSize(QtCore.QSize(0, 176))
        self.red_button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.red_button.setText("")
        self.red_button.setObjectName("red_button")
        self.colormix_buttons.addButton(self.red_button)
        self.gridLayout_2.addWidget(self.red_button, 1, 0, 1, 1)
        self.purple_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.purple_button.setMinimumSize(QtCore.QSize(0, 176))
        self.purple_button.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.purple_button.setText("")
        self.purple_button.setObjectName("purple_button")
        self.colormix_buttons.addButton(self.purple_button)
        self.gridLayout_2.addWidget(self.purple_button, 1, 5, 1, 1)
        self.relabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.relabel.setFont(font)
        self.relabel.setObjectName("relabel")
        self.gridLayout_2.addWidget(self.relabel, 0, 0, 1, 1)
        self.yelabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.yelabel.setFont(font)
        self.yelabel.setObjectName("yelabel")
        self.gridLayout_2.addWidget(self.yelabel, 0, 1, 1, 1)
        self.grlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.grlabel.setFont(font)
        self.grlabel.setObjectName("grlabel")
        self.gridLayout_2.addWidget(self.grlabel, 0, 2, 1, 1)
        self.cylabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.cylabel.setFont(font)
        self.cylabel.setObjectName("cylabel")
        self.gridLayout_2.addWidget(self.cylabel, 0, 3, 1, 1)
        self.blabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.blabel.setFont(font)
        self.blabel.setObjectName("blabel")
        self.gridLayout_2.addWidget(self.blabel, 0, 4, 1, 1)
        self.pulabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pulabel.setFont(font)
        self.pulabel.setObjectName("pulabel")
        self.gridLayout_2.addWidget(self.pulabel, 0, 5, 1, 1)
        self.image_worker.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.mxing_color = QtWidgets.QLabel(self.page_7)
        self.mxing_color.setGeometry(QtCore.QRect(0, 0, 1135, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mxing_color.sizePolicy().hasHeightForWidth())
        self.mxing_color.setSizePolicy(sizePolicy)
        self.mxing_color.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.mxing_color.setFont(font)
        self.mxing_color.setAlignment(QtCore.Qt.AlignCenter)
        self.mxing_color.setObjectName("mxing_color")
        self.shade_cm_label = QtWidgets.QLabel(self.page_7)
        self.shade_cm_label.setGeometry(QtCore.QRect(40, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.shade_cm_label.setFont(font)
        self.shade_cm_label.setObjectName("shade_cm_label")
        self.sat_cm_label = QtWidgets.QLabel(self.page_7)
        self.sat_cm_label.setGeometry(QtCore.QRect(40, 100, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.sat_cm_label.setFont(font)
        self.sat_cm_label.setObjectName("sat_cm_label")
        self.cbr = QtWidgets.QSlider(self.page_7)
        self.cbr.setGeometry(QtCore.QRect(180, 160, 911, 19))
        self.cbr.setMinimum(-50)
        self.cbr.setMaximum(50)
        self.cbr.setOrientation(QtCore.Qt.Horizontal)
        self.cbr.setObjectName("cbr")
        self.csat = QtWidgets.QSlider(self.page_7)
        self.csat.setGeometry(QtCore.QRect(180, 110, 911, 19))
        self.csat.setMinimum(-50)
        self.csat.setMaximum(50)
        self.csat.setOrientation(QtCore.Qt.Horizontal)
        self.csat.setObjectName("csat")
        self.csh = QtWidgets.QSlider(self.page_7)
        self.csh.setGeometry(QtCore.QRect(180, 60, 911, 19))
        self.csh.setMinimum(-50)
        self.csh.setMaximum(50)
        self.csh.setTracking(True)
        self.csh.setOrientation(QtCore.Qt.Horizontal)
        self.csh.setInvertedAppearance(False)
        self.csh.setObjectName("csh")
        self.bright_cm_label = QtWidgets.QLabel(self.page_7)
        self.bright_cm_label.setGeometry(QtCore.QRect(40, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.bright_cm_label.setFont(font)
        self.bright_cm_label.setObjectName("bright_cm_label")
        self.append_mix = QtWidgets.QPushButton(self.page_7)
        self.append_mix.setGeometry(QtCore.QRect(40, 200, 521, 40))
        self.append_mix.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.append_mix.setFont(font)
        self.append_mix.setObjectName("append_mix")
        self.cancel_mix = QtWidgets.QPushButton(self.page_7)
        self.cancel_mix.setGeometry(QtCore.QRect(570, 200, 521, 40))
        self.cancel_mix.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.cancel_mix.setFont(font)
        self.cancel_mix.setObjectName("cancel_mix")
        self.zero_label = QtWidgets.QLabel(self.page_7)
        self.zero_label.setGeometry(QtCore.QRect(620, 30, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.zero_label.setFont(font)
        self.zero_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.zero_label.setObjectName("zero_label")
        self.zero_label_2 = QtWidgets.QLabel(self.page_7)
        self.zero_label_2.setGeometry(QtCore.QRect(160, 30, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.zero_label_2.setFont(font)
        self.zero_label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.zero_label_2.setObjectName("zero_label_2")
        self.zero_label_3 = QtWidgets.QLabel(self.page_7)
        self.zero_label_3.setGeometry(QtCore.QRect(1080, 30, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.zero_label_3.setFont(font)
        self.zero_label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.zero_label_3.setObjectName("zero_label_3")
        self.image_worker.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.mxing_color_2 = QtWidgets.QLabel(self.page_8)
        self.mxing_color_2.setGeometry(QtCore.QRect(0, 0, 1135, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mxing_color_2.sizePolicy().hasHeightForWidth())
        self.mxing_color_2.setSizePolicy(sizePolicy)
        self.mxing_color_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.mxing_color_2.setFont(font)
        self.mxing_color_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mxing_color_2.setObjectName("mxing_color_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_8)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(270, 60, 581, 121))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.x_resize = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.x_resize.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.x_resize.setFont(font)
        self.x_resize.setMinimum(1)
        self.x_resize.setMaximum(8000)
        self.x_resize.setObjectName("x_resize")
        self.horizontalLayout_3.addWidget(self.x_resize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.y_resize = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.y_resize.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.y_resize.setFont(font)
        self.y_resize.setMinimum(1)
        self.y_resize.setMaximum(8000)
        self.y_resize.setObjectName("y_resize")
        self.horizontalLayout_3.addWidget(self.y_resize)
        self.y_set = QtWidgets.QPushButton(self.page_8)
        self.y_set.setGeometry(QtCore.QRect(710, 190, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.y_set.setFont(font)
        self.y_set.setObjectName("y_set")
        self.size_set = QtWidgets.QPushButton(self.page_8)
        self.size_set.setGeometry(QtCore.QRect(420, 190, 281, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.size_set.setFont(font)
        self.size_set.setObjectName("size_set")
        self.x_set = QtWidgets.QPushButton(self.page_8)
        self.x_set.setGeometry(QtCore.QRect(270, 190, 141, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.x_set.setFont(font)
        self.x_set.setObjectName("x_set")
        self.cursize_label = QtWidgets.QLabel(self.page_8)
        self.cursize_label.setGeometry(QtCore.QRect(446, 40, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.cursize_label.setFont(font)
        self.cursize_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cursize_label.setObjectName("cursize_label")
        self.image_worker.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.mxing_color_3 = QtWidgets.QLabel(self.page_9)
        self.mxing_color_3.setGeometry(QtCore.QRect(0, 0, 1135, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mxing_color_3.sizePolicy().hasHeightForWidth())
        self.mxing_color_3.setSizePolicy(sizePolicy)
        self.mxing_color_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.mxing_color_3.setFont(font)
        self.mxing_color_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mxing_color_3.setObjectName("mxing_color_3")
        self.mini_image = QtWidgets.QLabel(self.page_9)
        self.mini_image.setGeometry(QtCore.QRect(860, 30, 220, 220))
        self.mini_image.setText("")
        self.mini_image.setObjectName("mini_image")
        self.comboBox = QtWidgets.QComboBox(self.page_9)
        self.comboBox.setGeometry(QtCore.QRect(40, 100, 750, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.page_9)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 751, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.apply_preset = QtWidgets.QPushButton(self.page_9)
        self.apply_preset.setGeometry(QtCore.QRect(40, 180, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.apply_preset.setFont(font)
        self.apply_preset.setObjectName("apply_preset")
        self.create_preset = QtWidgets.QPushButton(self.page_9)
        self.create_preset.setGeometry(QtCore.QRect(290, 180, 250, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.create_preset.setFont(font)
        self.create_preset.setObjectName("create_preset")
        self.delete_preset = QtWidgets.QPushButton(self.page_9)
        self.delete_preset.setGeometry(QtCore.QRect(550, 180, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.delete_preset.setFont(font)
        self.delete_preset.setObjectName("delete_preset")
        self.image_worker.addWidget(self.page_9)
        self.verticalLayout_3.addWidget(self.image_worker)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.luminance_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.luminance_button.setMinimumSize(QtCore.QSize(0, 60))
        self.luminance_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.luminance_button.setFont(font)
        self.luminance_button.setToolTipDuration(4000)
        self.luminance_button.setText("")
        self.luminance_button.setObjectName("luminance_button")
        self.verticalLayout_2.addWidget(self.luminance_button)
        self.mixing_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mixing_button.setMinimumSize(QtCore.QSize(0, 60))
        self.mixing_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.mixing_button.setFont(font)
        self.mixing_button.setToolTipDuration(4000)
        self.mixing_button.setText("")
        self.mixing_button.setObjectName("mixing_button")
        self.verticalLayout_2.addWidget(self.mixing_button)
        self.palette_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.palette_button.setMinimumSize(QtCore.QSize(0, 60))
        self.palette_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.palette_button.setFont(font)
        self.palette_button.setToolTipDuration(4000)
        self.palette_button.setText("")
        self.palette_button.setObjectName("palette_button")
        self.verticalLayout_2.addWidget(self.palette_button)
        self.shadow_color_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.shadow_color_button.setMinimumSize(QtCore.QSize(0, 60))
        self.shadow_color_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.shadow_color_button.setFont(font)
        self.shadow_color_button.setToolTipDuration(4000)
        self.shadow_color_button.setText("")
        self.shadow_color_button.setObjectName("shadow_color_button")
        self.verticalLayout_2.addWidget(self.shadow_color_button)
        self.light_color_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_color_button.setMinimumSize(QtCore.QSize(0, 60))
        self.light_color_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.light_color_button.setFont(font)
        self.light_color_button.setToolTipDuration(4000)
        self.light_color_button.setText("")
        self.light_color_button.setObjectName("light_color_button")
        self.verticalLayout_2.addWidget(self.light_color_button)
        self.resize_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.resize_button.setMinimumSize(QtCore.QSize(0, 60))
        self.resize_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.resize_button.setFont(font)
        self.resize_button.setToolTipDuration(4000)
        self.resize_button.setText("")
        self.resize_button.setObjectName("resize_button")
        self.verticalLayout_2.addWidget(self.resize_button)
        self.spin_left_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.spin_left_button.setMinimumSize(QtCore.QSize(60, 60))
        self.spin_left_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.spin_left_button.setFont(font)
        self.spin_left_button.setToolTipDuration(4000)
        self.spin_left_button.setText("")
        self.spin_left_button.setObjectName("spin_left_button")
        self.verticalLayout_2.addWidget(self.spin_left_button)
        self.spin_right_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.spin_right_button.setMinimumSize(QtCore.QSize(0, 60))
        self.spin_right_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.spin_right_button.setFont(font)
        self.spin_right_button.setToolTipDuration(4000)
        self.spin_right_button.setText("")
        self.spin_right_button.setObjectName("spin_right_button")
        self.verticalLayout_2.addWidget(self.spin_right_button)
        self.presets_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.presets_button.setMinimumSize(QtCore.QSize(0, 60))
        self.presets_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.presets_button.setFont(font)
        self.presets_button.setToolTipDuration(3000)
        self.presets_button.setText("")
        self.presets_button.setObjectName("presets_button")
        self.verticalLayout_2.addWidget(self.presets_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        ProjectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProjectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDesign = QtWidgets.QMenu(self.menubar)
        self.menuDesign.setObjectName("menuDesign")
        self.menuPresets = QtWidgets.QMenu(self.menubar)
        self.menuPresets.setObjectName("menuPresets")
        ProjectWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(ProjectWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(ProjectWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionDelete = QtWidgets.QAction(ProjectWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionUndo = QtWidgets.QAction(ProjectWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(ProjectWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionYandex = QtWidgets.QAction(ProjectWindow)
        self.actionYandex.setObjectName("actionYandex")
        self.actionDarkened_foremost = QtWidgets.QAction(ProjectWindow)
        self.actionDarkened_foremost.setObjectName("actionDarkened_foremost")
        self.actionDark_Theme = QtWidgets.QAction(ProjectWindow)
        self.actionDark_Theme.setObjectName("actionDark_Theme")
        self.actionDark_Leaps = QtWidgets.QAction(ProjectWindow)
        self.actionDark_Leaps.setObjectName("actionDark_Leaps")
        self.actionGradient = QtWidgets.QAction(ProjectWindow)
        self.actionGradient.setObjectName("actionGradient")
        self.actionOrange_gradient = QtWidgets.QAction(ProjectWindow)
        self.actionOrange_gradient.setObjectName("actionOrange_gradient")
        self.actionGradark = QtWidgets.QAction(ProjectWindow)
        self.actionGradark.setObjectName("actionGradark")
        self.actionSave_preset = QtWidgets.QAction(ProjectWindow)
        self.actionSave_preset.setObjectName("actionSave_preset")
        self.actionDelete_all_custom_presets = QtWidgets.QAction(ProjectWindow)
        self.actionDelete_all_custom_presets.setObjectName("actionDelete_all_custom_presets")
        self.actionReset_all_changes = QtWidgets.QAction(ProjectWindow)
        self.actionReset_all_changes.setObjectName("actionReset_all_changes")
        self.menuProject.addAction(self.actionSave_as)
        self.menuProject.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionReset_all_changes)
        self.menuDesign.addAction(self.actionYandex)
        self.menuDesign.addAction(self.actionDarkened_foremost)
        self.menuDesign.addAction(self.actionDark_Theme)
        self.menuDesign.addAction(self.actionDark_Leaps)
        self.menuDesign.addAction(self.actionGradient)
        self.menuDesign.addAction(self.actionOrange_gradient)
        self.menuDesign.addAction(self.actionGradark)
        self.menuPresets.addAction(self.actionSave_preset)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuDesign.menuAction())
        self.menubar.addAction(self.menuPresets.menuAction())

        self.retranslateUi(ProjectWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.image_worker.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(ProjectWindow)

    def retranslateUi(self, ProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        ProjectWindow.setWindowTitle(_translate("ProjectWindow", "YAMCA: Project title"))
        self.label_luminance.setText(_translate("ProjectWindow", "Luminance"))
        self.label_contrast.setText(_translate("ProjectWindow", "Contrast"))
        self.accept_luminance.setText(_translate("ProjectWindow", "Accept"))
        self.lumilabel.setText(_translate("ProjectWindow", "Luminance/contrast"))
        self.lum_value_flag.setText(_translate("ProjectWindow", "0"))
        self.lum_value_flag_2.setText(_translate("ProjectWindow", "-150"))
        self.lum_value_flag_3.setText(_translate("ProjectWindow", "150"))
        self.lumilabel_2.setText(_translate("ProjectWindow", "Palette Change"))
        self.open_color_dialog.setText(_translate("ProjectWindow", "Open Color Dialog"))
        self.color_mixing_func_label.setText(_translate("ProjectWindow", "Color mixing"))
        self.relabel.setText(_translate("ProjectWindow", "Red"))
        self.yelabel.setText(_translate("ProjectWindow", "Yellow"))
        self.grlabel.setText(_translate("ProjectWindow", "Green"))
        self.cylabel.setText(_translate("ProjectWindow", "Cyan"))
        self.blabel.setText(_translate("ProjectWindow", "Blue"))
        self.pulabel.setText(_translate("ProjectWindow", "Purple"))
        self.mxing_color.setText(_translate("ProjectWindow", "Color mixing"))
        self.shade_cm_label.setText(_translate("ProjectWindow", "Shade"))
        self.sat_cm_label.setText(_translate("ProjectWindow", "Saturation"))
        self.bright_cm_label.setText(_translate("ProjectWindow", "Brightness"))
        self.append_mix.setText(_translate("ProjectWindow", "Apply"))
        self.cancel_mix.setText(_translate("ProjectWindow", "Back"))
        self.zero_label.setText(_translate("ProjectWindow", "0"))
        self.zero_label_2.setText(_translate("ProjectWindow", "-50"))
        self.zero_label_3.setText(_translate("ProjectWindow", "50"))
        self.mxing_color_2.setText(_translate("ProjectWindow", "Resize Image"))
        self.label.setText(_translate("ProjectWindow", "X:"))
        self.label_2.setText(_translate("ProjectWindow", "Y:"))
        self.y_set.setText(_translate("ProjectWindow", "Set Y only"))
        self.size_set.setText(_translate("ProjectWindow", "Resize an image"))
        self.x_set.setText(_translate("ProjectWindow", "Set X only"))
        self.cursize_label.setText(_translate("ProjectWindow", "Original size: "))
        self.mxing_color_3.setText(_translate("ProjectWindow", "Presets"))
        self.comboBox.setItemText(0, _translate("ProjectWindow", "Black & White"))
        self.comboBox.setItemText(1, _translate("ProjectWindow", "Negative"))
        self.comboBox.setItemText(2, _translate("ProjectWindow", "Sepia"))
        self.comboBox.setItemText(3, _translate("ProjectWindow", "Sketch"))
        self.comboBox.setItemText(4, _translate("ProjectWindow", "Pure colors"))
        self.label_3.setText(_translate("ProjectWindow", "Included 0 user presets"))
        self.apply_preset.setText(_translate("ProjectWindow", "Apply"))
        self.create_preset.setText(_translate("ProjectWindow", "Create New Preset"))
        self.delete_preset.setText(_translate("ProjectWindow", "Delete Preset"))
        self.luminance_button.setToolTip(_translate("ProjectWindow", "Luminance (B)"))
        self.mixing_button.setToolTip(_translate("ProjectWindow", "Color mixing (K)"))
        self.palette_button.setToolTip(_translate("ProjectWindow", "Paint the image (P)"))
        self.shadow_color_button.setToolTip(_translate("ProjectWindow", "Shadow shade (S)"))
        self.light_color_button.setToolTip(_translate("ProjectWindow", "Light shade (C)"))
        self.resize_button.setToolTip(_translate("ProjectWindow", "Resize (I)"))
        self.spin_left_button.setToolTip(_translate("ProjectWindow", "Rotate Left (L)"))
        self.spin_right_button.setToolTip(_translate("ProjectWindow", "Rotate Right (R)"))
        self.presets_button.setToolTip(_translate("ProjectWindow", "Presets (M)"))
        self.menuProject.setTitle(_translate("ProjectWindow", "File"))
        self.menuEdit.setTitle(_translate("ProjectWindow", "Edit"))
        self.menuDesign.setTitle(_translate("ProjectWindow", "Design"))
        self.menuPresets.setTitle(_translate("ProjectWindow", "Presets"))
        self.actionSave.setText(_translate("ProjectWindow", "Save"))
        self.actionSave_as.setText(_translate("ProjectWindow", "Save as..."))
        self.actionSave_as.setToolTip(_translate("ProjectWindow", "Save project as ..."))
        self.actionDelete.setText(_translate("ProjectWindow", "Delete"))
        self.actionUndo.setText(_translate("ProjectWindow", "Undo"))
        self.actionRedo.setText(_translate("ProjectWindow", "Redo"))
        self.actionYandex.setText(_translate("ProjectWindow", "Yandex foremost"))
        self.actionDarkened_foremost.setText(_translate("ProjectWindow", "Darkened foremost"))
        self.actionDark_Theme.setText(_translate("ProjectWindow", "Dark Theme"))
        self.actionDark_Leaps.setText(_translate("ProjectWindow", "Dark Leaps"))
        self.actionGradient.setText(_translate("ProjectWindow", "Gradient"))
        self.actionOrange_gradient.setText(_translate("ProjectWindow", "Orange gradient"))
        self.actionGradark.setText(_translate("ProjectWindow", "Gradark"))
        self.actionSave_preset.setText(_translate("ProjectWindow", "Save preset"))
        self.actionDelete_all_custom_presets.setText(_translate("ProjectWindow", "Delete all custom presets"))
        self.actionReset_all_changes.setText(_translate("ProjectWindow", "Reset all changes"))
