# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1201, 901))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.color_label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_4.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_4.setText("")
        self.color_label_4.setObjectName("color_label_4")
        self.gridLayout_3.addWidget(self.color_label_4, 3, 0, 1, 1)
        self.color_label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_8.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_8.setText("")
        self.color_label_8.setObjectName("color_label_8")
        self.gridLayout_3.addWidget(self.color_label_8, 7, 0, 1, 1)
        self.color_label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_2.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_2.setText("")
        self.color_label_2.setObjectName("color_label_2")
        self.gridLayout_3.addWidget(self.color_label_2, 1, 0, 1, 1)
        self.color_label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_7.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_7.setText("")
        self.color_label_7.setObjectName("color_label_7")
        self.gridLayout_3.addWidget(self.color_label_7, 6, 0, 1, 1)
        self.color_label_1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_1.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_1.setText("")
        self.color_label_1.setObjectName("color_label_1")
        self.gridLayout_3.addWidget(self.color_label_1, 0, 0, 1, 1)
        self.color_label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_6.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_6.setText("")
        self.color_label_6.setObjectName("color_label_6")
        self.gridLayout_3.addWidget(self.color_label_6, 5, 0, 1, 1)
        self.color_label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_3.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_3.setText("")
        self.color_label_3.setObjectName("color_label_3")
        self.gridLayout_3.addWidget(self.color_label_3, 2, 0, 1, 1)
        self.color_label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.color_label_5.setStyleSheet("background-color: \'#fc0\';")
        self.color_label_5.setText("")
        self.color_label_5.setObjectName("color_label_5")
        self.gridLayout_3.addWidget(self.color_label_5, 4, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1201, 881))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1201, 871))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.preferences = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.preferences.setFont(font)
        self.preferences.setObjectName("preferences")
        self.gridLayout.addWidget(self.preferences, 3, 1, 1, 1)
        self.newprojbut = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newprojbut.sizePolicy().hasHeightForWidth())
        self.newprojbut.setSizePolicy(sizePolicy)
        self.newprojbut.setMinimumSize(QtCore.QSize(380, 120))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.newprojbut.setFont(font)
        self.newprojbut.setObjectName("newprojbut")
        self.gridLayout.addWidget(self.newprojbut, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yalabel_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yalabel_4.sizePolicy().hasHeightForWidth())
        self.yalabel_4.setSizePolicy(sizePolicy)
        self.yalabel_4.setMinimumSize(QtCore.QSize(20, 100))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(55)
        self.yalabel_4.setFont(font)
        self.yalabel_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.yalabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yalabel_4.setObjectName("yalabel_4")
        self.horizontalLayout_4.addWidget(self.yalabel_4)
        self.mcalabel_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mcalabel_4.sizePolicy().hasHeightForWidth())
        self.mcalabel_4.setSizePolicy(sizePolicy)
        self.mcalabel_4.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(45)
        self.mcalabel_4.setFont(font)
        self.mcalabel_4.setObjectName("mcalabel_4")
        self.horizontalLayout_4.addWidget(self.mcalabel_4)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 7, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.exitbut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exitbut.setMinimumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.exitbut.setFont(font)
        self.exitbut.setObjectName("exitbut")
        self.horizontalLayout_5.addWidget(self.exitbut)
        self.changeaccb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.changeaccb.setMinimumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.changeaccb.setFont(font)
        self.changeaccb.setObjectName("changeaccb")
        self.horizontalLayout_5.addWidget(self.changeaccb)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1201, 871))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.back_from_pref = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.back_from_pref.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.back_from_pref.setFont(font)
        self.back_from_pref.setObjectName("back_from_pref")
        self.gridLayout_2.addWidget(self.back_from_pref, 6, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 1, 1, 1, 1)
        self.designcombo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.designcombo.setMinimumSize(QtCore.QSize(380, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.designcombo.setFont(font)
        self.designcombo.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.designcombo.setObjectName("designcombo")
        self.designcombo.addItem("")
        self.designcombo.addItem("")
        self.designcombo.addItem("")
        self.designcombo.addItem("")
        self.designcombo.addItem("")
        self.designcombo.addItem("")
        self.designcombo.addItem("")
        self.gridLayout_2.addWidget(self.designcombo, 3, 1, 1, 1)
        self.tutorialcheck = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.tutorialcheck.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.tutorialcheck.setFont(font)
        self.tutorialcheck.setObjectName("tutorialcheck")
        self.gridLayout_2.addWidget(self.tutorialcheck, 5, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 7, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yalabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yalabel_3.sizePolicy().hasHeightForWidth())
        self.yalabel_3.setSizePolicy(sizePolicy)
        self.yalabel_3.setMinimumSize(QtCore.QSize(20, 100))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(55)
        self.yalabel_3.setFont(font)
        self.yalabel_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.yalabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yalabel_3.setObjectName("yalabel_3")
        self.horizontalLayout_3.addWidget(self.yalabel_3)
        self.mcalabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mcalabel_3.sizePolicy().hasHeightForWidth())
        self.mcalabel_3.setSizePolicy(sizePolicy)
        self.mcalabel_3.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(45)
        self.mcalabel_3.setFont(font)
        self.mcalabel_3.setObjectName("mcalabel_3")
        self.horizontalLayout_3.addWidget(self.mcalabel_3)
        spacerItem9 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.random_design = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.random_design.setMinimumSize(QtCore.QSize(380, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.random_design.setFont(font)
        self.random_design.setObjectName("random_design")
        self.gridLayout_2.addWidget(self.random_design, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1201, 871))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.yalabel_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yalabel_5.sizePolicy().hasHeightForWidth())
        self.yalabel_5.setSizePolicy(sizePolicy)
        self.yalabel_5.setMinimumSize(QtCore.QSize(20, 100))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(55)
        self.yalabel_5.setFont(font)
        self.yalabel_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.yalabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yalabel_5.setObjectName("yalabel_5")
        self.horizontalLayout_6.addWidget(self.yalabel_5)
        self.mcalabel_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mcalabel_5.sizePolicy().hasHeightForWidth())
        self.mcalabel_5.setSizePolicy(sizePolicy)
        self.mcalabel_5.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(45)
        self.mcalabel_5.setFont(font)
        self.mcalabel_5.setObjectName("mcalabel_5")
        self.horizontalLayout_6.addWidget(self.mcalabel_5)
        spacerItem11 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem12, 1, 1, 1, 1)
        self.back_from_pref_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.back_from_pref_2.setMinimumSize(QtCore.QSize(0, 111))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.back_from_pref_2.setFont(font)
        self.back_from_pref_2.setObjectName("back_from_pref_2")
        self.gridLayout_4.addWidget(self.back_from_pref_2, 7, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 8, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 4, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 6, 1, 1, 1)
        self.startproject = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.startproject.setMinimumSize(QtCore.QSize(380, 112))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startproject.setFont(font)
        self.startproject.setObjectName("startproject")
        self.gridLayout_4.addWidget(self.startproject, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.authority = QtWidgets.QLabel(self.centralwidget)
        self.authority.setGeometry(QtCore.QRect(0, 830, 1200, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authority.sizePolicy().hasHeightForWidth())
        self.authority.setSizePolicy(sizePolicy)
        self.authority.setMaximumSize(QtCore.QSize(1200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Cond")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.authority.setFont(font)
        self.authority.setAutoFillBackground(False)
        self.authority.setAlignment(QtCore.Qt.AlignCenter)
        self.authority.setObjectName("authority")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YaMCA v0.1 alpha (.2019)"))
        self.preferences.setText(_translate("MainWindow", "⚙ Preferences ⚙"))
        self.newprojbut.setText(_translate("MainWindow", "Create a Masterpiece"))
        self.yalabel_4.setText(_translate("MainWindow", "Ya"))
        self.mcalabel_4.setText(_translate("MainWindow", "MCA"))
        self.exitbut.setText(_translate("MainWindow", "Exit"))
        self.changeaccb.setText(_translate("MainWindow", "Change Account"))
        self.back_from_pref.setText(_translate("MainWindow", "Back"))
        self.designcombo.setItemText(0, _translate("MainWindow", "Yandex Colored Design"))
        self.designcombo.setItemText(1, _translate("MainWindow", "Darkened  Foremost"))
        self.designcombo.setItemText(2, _translate("MainWindow", "Dark Theme"))
        self.designcombo.setItemText(3, _translate("MainWindow", "Dark Leaps"))
        self.designcombo.setItemText(4, _translate("MainWindow", "Gradient"))
        self.designcombo.setItemText(5, _translate("MainWindow", "Orange gradient"))
        self.designcombo.setItemText(6, _translate("MainWindow", "GraDark"))
        self.tutorialcheck.setText(_translate("MainWindow", "Set memory usage limit"))
        self.yalabel_3.setText(_translate("MainWindow", "Ya"))
        self.mcalabel_3.setText(_translate("MainWindow", "MCA"))
        self.random_design.setText(_translate("MainWindow", "Random Design"))
        self.yalabel_5.setText(_translate("MainWindow", "Ya"))
        self.mcalabel_5.setText(_translate("MainWindow", "MCA"))
        self.back_from_pref_2.setText(_translate("MainWindow", "Back"))
        self.startproject.setText(_translate("MainWindow", "New Project"))
        self.authority.setText(_translate("MainWindow", "©2019, Author: Urzhumov V.A.; In development since 10.2019. Not available for commercial use.  All rights reserved."))
